/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import javax.swing.UIManager;

/**
 *
 * @author miller.barrera
 */
public class SelectRoutines extends javax.swing.JFrame {

    /**
     * Creates new form SelectRoutines
     */
    public SelectRoutines() {
        
         try {

            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectRoutines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectRoutines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectRoutines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectRoutines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelRoutines = new javax.swing.JPanel();
        comoRoutines = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBackgroud = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTitleName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rutinas");
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Bienvenid@");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, -1));

        panelRoutines.setBackground(new java.awt.Color(255, 255, 255));
        panelRoutines.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 204, 255), new java.awt.Color(51, 0, 204))));

        comoRoutines.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comoRoutines.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Rutina:", "Peso Ideal – Mantenerse", "Sobre Peso – Bajar", "Peso Ideal – Sacar Musculo" }));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\miller.barrera\\Pictures\\person.png")); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\miller.barrera\\Pictures\\run.png")); // NOI18N
        jLabel5.setText("jLabel4");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\miller.barrera\\Pictures\\muscle.png")); // NOI18N
        jLabel6.setText("jLabel4");

        javax.swing.GroupLayout panelRoutinesLayout = new javax.swing.GroupLayout(panelRoutines);
        panelRoutines.setLayout(panelRoutinesLayout);
        panelRoutinesLayout.setHorizontalGroup(
            panelRoutinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoutinesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRoutinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoutinesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(comoRoutines, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoutinesLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        panelRoutinesLayout.setVerticalGroup(
            panelRoutinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoutinesLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(comoRoutines, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(panelRoutinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        getContentPane().add(panelRoutines, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 370, 400));

        lblBackgroud.setIcon(new javax.swing.ImageIcon("C:\\Users\\miller.barrera\\Pictures\\routines.jpg")); // NOI18N
        getContentPane().add(lblBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 590, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\miller.barrera\\Pictures\\gymicon.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 50));

        lblTitleName.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblTitleName.setForeground(new java.awt.Color(255, 51, 102));
        getContentPane().add(lblTitleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 0));
        jLabel3.setText("Selecciona la rutina que deseas realizar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comoRoutines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBackgroud;
    private javax.swing.JLabel lblTitleName;
    private javax.swing.JPanel panelRoutines;
    // End of variables declaration//GEN-END:variables
}
